# Numpy

This is numerical python, workinhg with arrays, 

to use you import the module as alias np

- its also a fuction for working with linear algebra, fouroer transform and matrices.

- Its an improve list, and is more faster than lost(stored in one place,cpu), they objects called ndarray(for fast use and resources)

- ndarray can take (list, tuple,)

# Dimention in array

- 1 dimentina arrays are called - vector 
- 2 dimentional array are called matrix - nested list
- 3 dimentional are called tensor

- You can check the array attributes 

    - (shape- Checks the dimention(size of element ),
    - size - checking the number of elements i  array
    - and type checking the arrays-)
    - indexing and sclicing, respaing and flatening 

- Operations, - arithmetic, broadcasting, elemt-wise, matrix(dot product, cross product, transpose)

- Manipulaion, concatinating and spliting, satcking and unstacking, inserting and deleteing elements

- Statistical function(descriptive statistics[mean, mode,median,variance, standard deviation],)

- Random generation( uniform, nromal, binomial distribution) * random seed, and sampling



In [3]:
import numpy as np
# 0-d array
# ndarray created using list
arr = np.array([1,2,3,4,5])

print(arr)

# checking the type of array(ndarray)

print(type(arr))

# to check version of numpy
print(np.__version__)

# 2-d array

arr_2d = np.array([[11,22,33,44], [12,11,12,111]])

print()
print(arr_2d.size)
print(arr.dtype)

print()

arr_3d = np.array([[1,2,3],[4,5,6],[11,2,3]])

# check the type of array
print(arr_2d.ndim)

print()

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.26.1

8
int64

2



In [14]:
# sclicing & indexing

numbers = (11,2,3,4,22,22)

print(numbers[0])

print(numbers[1:4])

mult_num = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print(mult_num[0:2,1:])

# reshaping array

reshaped = mult_num.flatten() #revel

print(reshaped)

11
(2, 3, 4)

[[2 3]
 [5 6]]
[1 2 3 4 5 6 7 8 9]


In [18]:
log_array = np.log(numbers)

print(log_array)

print()
sin_array = np.sin(numbers)

print(sin_array)

print()

cosine_array = np.cos(numbers)

print(cosine_array)

[2.39789527 0.69314718 1.09861229 1.38629436 3.09104245 3.09104245]

[-0.99999021  0.90929743  0.14112001 -0.7568025  -0.00885131 -0.00885131]

[ 0.0044257  -0.41614684 -0.9899925  -0.65364362 -0.99996083 -0.99996083]


## Statistcial fun

This are basic statistics, descriptive statistics 

- mean, median, mode, variance, standard deviation

    - Mean - avarage value of data set
    - median - middle value of data(when data sis arragned in orderly manner)
    - mode - is the vlaue that occurs the most, more than once 
    - variance - measure the spread of variability(avarange of the squared diffrence between each value and mean) [ high varaince means dats is spread out, while low state data is clustered closely around mean]