# Numpy

This is numerical python, workinhg with arrays, 

to use you import the module as alias np

- its also a fuction for working with linear algebra, fouroer transform and matrices.

- Its an improve list, and is more faster than lost(stored in one place,cpu), they objects called ndarray(for fast use and resources)

- ndarray can take (list, tuple,)

# Dimention in array

- 1 dimentina arrays are called - vector 
- 2 dimentional array are called matrix - nested list
- 3 dimentional are called tensor

- You can check the array attributes 

    - (shape- Checks the dimention(size of element ),
    - size - checking the number of elements i  array
    - and type checking the arrays-)
    - indexing and sclicing, respaing and flatening 

- Operations, - arithmetic, broadcasting, elemt-wise, matrix(dot product, cross product, transpose)

- Manipulaion, concatinating and spliting, satcking and unstacking, inserting and deleteing elements

- Statistical function(descriptive statistics[mean, mode,median,variance, standard deviation],)

- Random generation( uniform, nromal, binomial distribution) * random seed, and sampling



In [3]:
import numpy as np
# 0-d array
# ndarray created using list
arr = np.array([1,2,3,4,5])

print(arr)

# checking the type of array(ndarray)

print(type(arr))

# to check version of numpy
print(np.__version__)

# 2-d array

arr_2d = np.array([[11,22,33,44], [12,11,12,111]])

print()
print(arr_2d.size)
print(arr.dtype)

print()

arr_3d = np.array([[1,2,3],[4,5,6],[11,2,3]])

# check the type of array
print(arr_2d.ndim)

print()

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.26.1

8
int64

2



In [14]:
# sclicing & indexing

numbers = (11,2,3,4,22,22)

print(numbers[0])

print(numbers[1:4])

mult_num = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print(mult_num[0:2,1:])

# reshaping array

reshaped = mult_num.flatten() #revel

print(reshaped)

11
(2, 3, 4)

[[2 3]
 [5 6]]
[1 2 3 4 5 6 7 8 9]
